# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grep/bro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grep/bro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grep/bro/CMakeFiles /home/grep/bro//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grep/bro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bro

# Build rule for target.
bro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bro
.PHONY : bro

# fast build rule for target.
bro/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/build
.PHONY : bro/fast

src/commands/absorb.o: src/commands/absorb.c.o
.PHONY : src/commands/absorb.o

# target to build an object file
src/commands/absorb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/absorb.c.o
.PHONY : src/commands/absorb.c.o

src/commands/absorb.i: src/commands/absorb.c.i
.PHONY : src/commands/absorb.i

# target to preprocess a source file
src/commands/absorb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/absorb.c.i
.PHONY : src/commands/absorb.c.i

src/commands/absorb.s: src/commands/absorb.c.s
.PHONY : src/commands/absorb.s

# target to generate assembly for a file
src/commands/absorb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/absorb.c.s
.PHONY : src/commands/absorb.c.s

src/commands/amend-yeet.o: src/commands/amend-yeet.c.o
.PHONY : src/commands/amend-yeet.o

# target to build an object file
src/commands/amend-yeet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/amend-yeet.c.o
.PHONY : src/commands/amend-yeet.c.o

src/commands/amend-yeet.i: src/commands/amend-yeet.c.i
.PHONY : src/commands/amend-yeet.i

# target to preprocess a source file
src/commands/amend-yeet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/amend-yeet.c.i
.PHONY : src/commands/amend-yeet.c.i

src/commands/amend-yeet.s: src/commands/amend-yeet.c.s
.PHONY : src/commands/amend-yeet.s

# target to generate assembly for a file
src/commands/amend-yeet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/amend-yeet.c.s
.PHONY : src/commands/amend-yeet.c.s

src/commands/apply-mail.o: src/commands/apply-mail.c.o
.PHONY : src/commands/apply-mail.o

# target to build an object file
src/commands/apply-mail.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/apply-mail.c.o
.PHONY : src/commands/apply-mail.c.o

src/commands/apply-mail.i: src/commands/apply-mail.c.i
.PHONY : src/commands/apply-mail.i

# target to preprocess a source file
src/commands/apply-mail.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/apply-mail.c.i
.PHONY : src/commands/apply-mail.c.i

src/commands/apply-mail.s: src/commands/apply-mail.c.s
.PHONY : src/commands/apply-mail.s

# target to generate assembly for a file
src/commands/apply-mail.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/apply-mail.c.s
.PHONY : src/commands/apply-mail.c.s

src/commands/archive-vibes.o: src/commands/archive-vibes.c.o
.PHONY : src/commands/archive-vibes.o

# target to build an object file
src/commands/archive-vibes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/archive-vibes.c.o
.PHONY : src/commands/archive-vibes.c.o

src/commands/archive-vibes.i: src/commands/archive-vibes.c.i
.PHONY : src/commands/archive-vibes.i

# target to preprocess a source file
src/commands/archive-vibes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/archive-vibes.c.i
.PHONY : src/commands/archive-vibes.c.i

src/commands/archive-vibes.s: src/commands/archive-vibes.c.s
.PHONY : src/commands/archive-vibes.s

# target to generate assembly for a file
src/commands/archive-vibes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/archive-vibes.c.s
.PHONY : src/commands/archive-vibes.c.s

src/commands/blame-grep.o: src/commands/blame-grep.c.o
.PHONY : src/commands/blame-grep.o

# target to build an object file
src/commands/blame-grep.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/blame-grep.c.o
.PHONY : src/commands/blame-grep.c.o

src/commands/blame-grep.i: src/commands/blame-grep.c.i
.PHONY : src/commands/blame-grep.i

# target to preprocess a source file
src/commands/blame-grep.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/blame-grep.c.i
.PHONY : src/commands/blame-grep.c.i

src/commands/blame-grep.s: src/commands/blame-grep.c.s
.PHONY : src/commands/blame-grep.s

# target to generate assembly for a file
src/commands/blame-grep.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/blame-grep.c.s
.PHONY : src/commands/blame-grep.c.s

src/commands/bro-doctor.o: src/commands/bro-doctor.c.o
.PHONY : src/commands/bro-doctor.o

# target to build an object file
src/commands/bro-doctor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/bro-doctor.c.o
.PHONY : src/commands/bro-doctor.c.o

src/commands/bro-doctor.i: src/commands/bro-doctor.c.i
.PHONY : src/commands/bro-doctor.i

# target to preprocess a source file
src/commands/bro-doctor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/bro-doctor.c.i
.PHONY : src/commands/bro-doctor.c.i

src/commands/bro-doctor.s: src/commands/bro-doctor.c.s
.PHONY : src/commands/bro-doctor.s

# target to generate assembly for a file
src/commands/bro-doctor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/bro-doctor.c.s
.PHONY : src/commands/bro-doctor.c.s

src/commands/clean-house.o: src/commands/clean-house.c.o
.PHONY : src/commands/clean-house.o

# target to build an object file
src/commands/clean-house.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/clean-house.c.o
.PHONY : src/commands/clean-house.c.o

src/commands/clean-house.i: src/commands/clean-house.c.i
.PHONY : src/commands/clean-house.i

# target to preprocess a source file
src/commands/clean-house.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/clean-house.c.i
.PHONY : src/commands/clean-house.c.i

src/commands/clean-house.s: src/commands/clean-house.c.s
.PHONY : src/commands/clean-house.s

# target to generate assembly for a file
src/commands/clean-house.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/clean-house.c.s
.PHONY : src/commands/clean-house.c.s

src/commands/config-vibe.o: src/commands/config-vibe.c.o
.PHONY : src/commands/config-vibe.o

# target to build an object file
src/commands/config-vibe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/config-vibe.c.o
.PHONY : src/commands/config-vibe.c.o

src/commands/config-vibe.i: src/commands/config-vibe.c.i
.PHONY : src/commands/config-vibe.i

# target to preprocess a source file
src/commands/config-vibe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/config-vibe.c.i
.PHONY : src/commands/config-vibe.c.i

src/commands/config-vibe.s: src/commands/config-vibe.c.s
.PHONY : src/commands/config-vibe.s

# target to generate assembly for a file
src/commands/config-vibe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/config-vibe.c.s
.PHONY : src/commands/config-vibe.c.s

src/commands/delete-bro.o: src/commands/delete-bro.c.o
.PHONY : src/commands/delete-bro.o

# target to build an object file
src/commands/delete-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/delete-bro.c.o
.PHONY : src/commands/delete-bro.c.o

src/commands/delete-bro.i: src/commands/delete-bro.c.i
.PHONY : src/commands/delete-bro.i

# target to preprocess a source file
src/commands/delete-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/delete-bro.c.i
.PHONY : src/commands/delete-bro.c.i

src/commands/delete-bro.s: src/commands/delete-bro.c.s
.PHONY : src/commands/delete-bro.s

# target to generate assembly for a file
src/commands/delete-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/delete-bro.c.s
.PHONY : src/commands/delete-bro.c.s

src/commands/detective.o: src/commands/detective.c.o
.PHONY : src/commands/detective.o

# target to build an object file
src/commands/detective.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/detective.c.o
.PHONY : src/commands/detective.c.o

src/commands/detective.i: src/commands/detective.c.i
.PHONY : src/commands/detective.i

# target to preprocess a source file
src/commands/detective.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/detective.c.i
.PHONY : src/commands/detective.c.i

src/commands/detective.s: src/commands/detective.c.s
.PHONY : src/commands/detective.s

# target to generate assembly for a file
src/commands/detective.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/detective.c.s
.PHONY : src/commands/detective.c.s

src/commands/diff-bro.o: src/commands/diff-bro.c.o
.PHONY : src/commands/diff-bro.o

# target to build an object file
src/commands/diff-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/diff-bro.c.o
.PHONY : src/commands/diff-bro.c.o

src/commands/diff-bro.i: src/commands/diff-bro.c.i
.PHONY : src/commands/diff-bro.i

# target to preprocess a source file
src/commands/diff-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/diff-bro.c.i
.PHONY : src/commands/diff-bro.c.i

src/commands/diff-bro.s: src/commands/diff-bro.c.s
.PHONY : src/commands/diff-bro.s

# target to generate assembly for a file
src/commands/diff-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/diff-bro.c.s
.PHONY : src/commands/diff-bro.c.s

src/commands/drip.o: src/commands/drip.c.o
.PHONY : src/commands/drip.o

# target to build an object file
src/commands/drip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/drip.c.o
.PHONY : src/commands/drip.c.o

src/commands/drip.i: src/commands/drip.c.i
.PHONY : src/commands/drip.i

# target to preprocess a source file
src/commands/drip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/drip.c.i
.PHONY : src/commands/drip.c.i

src/commands/drip.s: src/commands/drip.c.s
.PHONY : src/commands/drip.s

# target to generate assembly for a file
src/commands/drip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/drip.c.s
.PHONY : src/commands/drip.c.s

src/commands/expose.o: src/commands/expose.c.o
.PHONY : src/commands/expose.o

# target to build an object file
src/commands/expose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/expose.c.o
.PHONY : src/commands/expose.c.o

src/commands/expose.i: src/commands/expose.c.i
.PHONY : src/commands/expose.i

# target to preprocess a source file
src/commands/expose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/expose.c.i
.PHONY : src/commands/expose.c.i

src/commands/expose.s: src/commands/expose.c.s
.PHONY : src/commands/expose.s

# target to generate assembly for a file
src/commands/expose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/expose.c.s
.PHONY : src/commands/expose.c.s

src/commands/force-launch.o: src/commands/force-launch.c.o
.PHONY : src/commands/force-launch.o

# target to build an object file
src/commands/force-launch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/force-launch.c.o
.PHONY : src/commands/force-launch.c.o

src/commands/force-launch.i: src/commands/force-launch.c.i
.PHONY : src/commands/force-launch.i

# target to preprocess a source file
src/commands/force-launch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/force-launch.c.i
.PHONY : src/commands/force-launch.c.i

src/commands/force-launch.s: src/commands/force-launch.c.s
.PHONY : src/commands/force-launch.s

# target to generate assembly for a file
src/commands/force-launch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/force-launch.c.s
.PHONY : src/commands/force-launch.c.s

src/commands/fuse.o: src/commands/fuse.c.o
.PHONY : src/commands/fuse.o

# target to build an object file
src/commands/fuse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/fuse.c.o
.PHONY : src/commands/fuse.c.o

src/commands/fuse.i: src/commands/fuse.c.i
.PHONY : src/commands/fuse.i

# target to preprocess a source file
src/commands/fuse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/fuse.c.i
.PHONY : src/commands/fuse.c.i

src/commands/fuse.s: src/commands/fuse.c.s
.PHONY : src/commands/fuse.s

# target to generate assembly for a file
src/commands/fuse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/fuse.c.s
.PHONY : src/commands/fuse.c.s

src/commands/grep-it.o: src/commands/grep-it.c.o
.PHONY : src/commands/grep-it.o

# target to build an object file
src/commands/grep-it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/grep-it.c.o
.PHONY : src/commands/grep-it.c.o

src/commands/grep-it.i: src/commands/grep-it.c.i
.PHONY : src/commands/grep-it.i

# target to preprocess a source file
src/commands/grep-it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/grep-it.c.i
.PHONY : src/commands/grep-it.c.i

src/commands/grep-it.s: src/commands/grep-it.c.s
.PHONY : src/commands/grep-it.s

# target to generate assembly for a file
src/commands/grep-it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/grep-it.c.s
.PHONY : src/commands/grep-it.c.s

src/commands/hard-undo.o: src/commands/hard-undo.c.o
.PHONY : src/commands/hard-undo.o

# target to build an object file
src/commands/hard-undo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hard-undo.c.o
.PHONY : src/commands/hard-undo.c.o

src/commands/hard-undo.i: src/commands/hard-undo.c.i
.PHONY : src/commands/hard-undo.i

# target to preprocess a source file
src/commands/hard-undo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hard-undo.c.i
.PHONY : src/commands/hard-undo.c.i

src/commands/hard-undo.s: src/commands/hard-undo.c.s
.PHONY : src/commands/hard-undo.s

# target to generate assembly for a file
src/commands/hard-undo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hard-undo.c.s
.PHONY : src/commands/hard-undo.c.s

src/commands/hash-slap.o: src/commands/hash-slap.c.o
.PHONY : src/commands/hash-slap.o

# target to build an object file
src/commands/hash-slap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hash-slap.c.o
.PHONY : src/commands/hash-slap.c.o

src/commands/hash-slap.i: src/commands/hash-slap.c.i
.PHONY : src/commands/hash-slap.i

# target to preprocess a source file
src/commands/hash-slap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hash-slap.c.i
.PHONY : src/commands/hash-slap.c.i

src/commands/hash-slap.s: src/commands/hash-slap.c.s
.PHONY : src/commands/hash-slap.s

# target to generate assembly for a file
src/commands/hash-slap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hash-slap.c.s
.PHONY : src/commands/hash-slap.c.s

src/commands/hide.o: src/commands/hide.c.o
.PHONY : src/commands/hide.o

# target to build an object file
src/commands/hide.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hide.c.o
.PHONY : src/commands/hide.c.o

src/commands/hide.i: src/commands/hide.c.i
.PHONY : src/commands/hide.i

# target to preprocess a source file
src/commands/hide.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hide.c.i
.PHONY : src/commands/hide.c.i

src/commands/hide.s: src/commands/hide.c.s
.PHONY : src/commands/hide.s

# target to generate assembly for a file
src/commands/hide.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/hide.c.s
.PHONY : src/commands/hide.c.s

src/commands/ignore-bro.o: src/commands/ignore-bro.c.o
.PHONY : src/commands/ignore-bro.o

# target to build an object file
src/commands/ignore-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ignore-bro.c.o
.PHONY : src/commands/ignore-bro.c.o

src/commands/ignore-bro.i: src/commands/ignore-bro.c.i
.PHONY : src/commands/ignore-bro.i

# target to preprocess a source file
src/commands/ignore-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ignore-bro.c.i
.PHONY : src/commands/ignore-bro.c.i

src/commands/ignore-bro.s: src/commands/ignore-bro.c.s
.PHONY : src/commands/ignore-bro.s

# target to generate assembly for a file
src/commands/ignore-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ignore-bro.c.s
.PHONY : src/commands/ignore-bro.c.s

src/commands/init.o: src/commands/init.c.o
.PHONY : src/commands/init.o

# target to build an object file
src/commands/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/init.c.o
.PHONY : src/commands/init.c.o

src/commands/init.i: src/commands/init.c.i
.PHONY : src/commands/init.i

# target to preprocess a source file
src/commands/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/init.c.i
.PHONY : src/commands/init.c.i

src/commands/init.s: src/commands/init.c.s
.PHONY : src/commands/init.s

# target to generate assembly for a file
src/commands/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/init.c.s
.PHONY : src/commands/init.c.s

src/commands/launch.o: src/commands/launch.c.o
.PHONY : src/commands/launch.o

# target to build an object file
src/commands/launch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/launch.c.o
.PHONY : src/commands/launch.c.o

src/commands/launch.i: src/commands/launch.c.i
.PHONY : src/commands/launch.i

# target to preprocess a source file
src/commands/launch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/launch.c.i
.PHONY : src/commands/launch.c.i

src/commands/launch.s: src/commands/launch.c.s
.PHONY : src/commands/launch.s

# target to generate assembly for a file
src/commands/launch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/launch.c.s
.PHONY : src/commands/launch.c.s

src/commands/live.o: src/commands/live.c.o
.PHONY : src/commands/live.o

# target to build an object file
src/commands/live.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/live.c.o
.PHONY : src/commands/live.c.o

src/commands/live.i: src/commands/live.c.i
.PHONY : src/commands/live.i

# target to preprocess a source file
src/commands/live.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/live.c.i
.PHONY : src/commands/live.c.i

src/commands/live.s: src/commands/live.c.s
.PHONY : src/commands/live.s

# target to generate assembly for a file
src/commands/live.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/live.c.s
.PHONY : src/commands/live.c.s

src/commands/ls-bro.o: src/commands/ls-bro.c.o
.PHONY : src/commands/ls-bro.o

# target to build an object file
src/commands/ls-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ls-bro.c.o
.PHONY : src/commands/ls-bro.c.o

src/commands/ls-bro.i: src/commands/ls-bro.c.i
.PHONY : src/commands/ls-bro.i

# target to preprocess a source file
src/commands/ls-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ls-bro.c.i
.PHONY : src/commands/ls-bro.c.i

src/commands/ls-bro.s: src/commands/ls-bro.c.s
.PHONY : src/commands/ls-bro.s

# target to generate assembly for a file
src/commands/ls-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/ls-bro.c.s
.PHONY : src/commands/ls-bro.c.s

src/commands/multiverse.o: src/commands/multiverse.c.o
.PHONY : src/commands/multiverse.o

# target to build an object file
src/commands/multiverse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/multiverse.c.o
.PHONY : src/commands/multiverse.c.o

src/commands/multiverse.i: src/commands/multiverse.c.i
.PHONY : src/commands/multiverse.i

# target to preprocess a source file
src/commands/multiverse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/multiverse.c.i
.PHONY : src/commands/multiverse.c.i

src/commands/multiverse.s: src/commands/multiverse.c.s
.PHONY : src/commands/multiverse.s

# target to generate assembly for a file
src/commands/multiverse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/multiverse.c.s
.PHONY : src/commands/multiverse.c.s

src/commands/new-squad.o: src/commands/new-squad.c.o
.PHONY : src/commands/new-squad.o

# target to build an object file
src/commands/new-squad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/new-squad.c.o
.PHONY : src/commands/new-squad.c.o

src/commands/new-squad.i: src/commands/new-squad.c.i
.PHONY : src/commands/new-squad.i

# target to preprocess a source file
src/commands/new-squad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/new-squad.c.i
.PHONY : src/commands/new-squad.c.i

src/commands/new-squad.s: src/commands/new-squad.c.s
.PHONY : src/commands/new-squad.s

# target to generate assembly for a file
src/commands/new-squad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/new-squad.c.s
.PHONY : src/commands/new-squad.c.s

src/commands/nickname.o: src/commands/nickname.c.o
.PHONY : src/commands/nickname.o

# target to build an object file
src/commands/nickname.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/nickname.c.o
.PHONY : src/commands/nickname.c.o

src/commands/nickname.i: src/commands/nickname.c.i
.PHONY : src/commands/nickname.i

# target to preprocess a source file
src/commands/nickname.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/nickname.c.i
.PHONY : src/commands/nickname.c.i

src/commands/nickname.s: src/commands/nickname.c.s
.PHONY : src/commands/nickname.s

# target to generate assembly for a file
src/commands/nickname.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/nickname.c.s
.PHONY : src/commands/nickname.c.s

src/commands/only-fans.o: src/commands/only-fans.c.o
.PHONY : src/commands/only-fans.o

# target to build an object file
src/commands/only-fans.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/only-fans.c.o
.PHONY : src/commands/only-fans.c.o

src/commands/only-fans.i: src/commands/only-fans.c.i
.PHONY : src/commands/only-fans.i

# target to preprocess a source file
src/commands/only-fans.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/only-fans.c.i
.PHONY : src/commands/only-fans.c.i

src/commands/only-fans.s: src/commands/only-fans.c.s
.PHONY : src/commands/only-fans.s

# target to generate assembly for a file
src/commands/only-fans.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/only-fans.c.s
.PHONY : src/commands/only-fans.c.s

src/commands/oopsie.o: src/commands/oopsie.c.o
.PHONY : src/commands/oopsie.o

# target to build an object file
src/commands/oopsie.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/oopsie.c.o
.PHONY : src/commands/oopsie.c.o

src/commands/oopsie.i: src/commands/oopsie.c.i
.PHONY : src/commands/oopsie.i

# target to preprocess a source file
src/commands/oopsie.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/oopsie.c.i
.PHONY : src/commands/oopsie.c.i

src/commands/oopsie.s: src/commands/oopsie.c.s
.PHONY : src/commands/oopsie.s

# target to generate assembly for a file
src/commands/oopsie.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/oopsie.c.s
.PHONY : src/commands/oopsie.c.s

src/commands/panic-revert.o: src/commands/panic-revert.c.o
.PHONY : src/commands/panic-revert.o

# target to build an object file
src/commands/panic-revert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/panic-revert.c.o
.PHONY : src/commands/panic-revert.c.o

src/commands/panic-revert.i: src/commands/panic-revert.c.i
.PHONY : src/commands/panic-revert.i

# target to preprocess a source file
src/commands/panic-revert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/panic-revert.c.i
.PHONY : src/commands/panic-revert.c.i

src/commands/panic-revert.s: src/commands/panic-revert.c.s
.PHONY : src/commands/panic-revert.s

# target to generate assembly for a file
src/commands/panic-revert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/panic-revert.c.s
.PHONY : src/commands/panic-revert.c.s

src/commands/patch-mail.o: src/commands/patch-mail.c.o
.PHONY : src/commands/patch-mail.o

# target to build an object file
src/commands/patch-mail.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/patch-mail.c.o
.PHONY : src/commands/patch-mail.c.o

src/commands/patch-mail.i: src/commands/patch-mail.c.i
.PHONY : src/commands/patch-mail.i

# target to preprocess a source file
src/commands/patch-mail.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/patch-mail.c.i
.PHONY : src/commands/patch-mail.c.i

src/commands/patch-mail.s: src/commands/patch-mail.c.s
.PHONY : src/commands/patch-mail.s

# target to generate assembly for a file
src/commands/patch-mail.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/patch-mail.c.s
.PHONY : src/commands/patch-mail.c.s

src/commands/peek.o: src/commands/peek.c.o
.PHONY : src/commands/peek.o

# target to build an object file
src/commands/peek.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/peek.c.o
.PHONY : src/commands/peek.c.o

src/commands/peek.i: src/commands/peek.c.i
.PHONY : src/commands/peek.i

# target to preprocess a source file
src/commands/peek.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/peek.c.i
.PHONY : src/commands/peek.c.i

src/commands/peek.s: src/commands/peek.c.s
.PHONY : src/commands/peek.s

# target to generate assembly for a file
src/commands/peek.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/peek.c.s
.PHONY : src/commands/peek.c.s

src/commands/range-roast.o: src/commands/range-roast.c.o
.PHONY : src/commands/range-roast.o

# target to build an object file
src/commands/range-roast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/range-roast.c.o
.PHONY : src/commands/range-roast.c.o

src/commands/range-roast.i: src/commands/range-roast.c.i
.PHONY : src/commands/range-roast.i

# target to preprocess a source file
src/commands/range-roast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/range-roast.c.i
.PHONY : src/commands/range-roast.c.i

src/commands/range-roast.s: src/commands/range-roast.c.s
.PHONY : src/commands/range-roast.s

# target to generate assembly for a file
src/commands/range-roast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/range-roast.c.s
.PHONY : src/commands/range-roast.c.s

src/commands/reflog-yap.o: src/commands/reflog-yap.c.o
.PHONY : src/commands/reflog-yap.o

# target to build an object file
src/commands/reflog-yap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/reflog-yap.c.o
.PHONY : src/commands/reflog-yap.c.o

src/commands/reflog-yap.i: src/commands/reflog-yap.c.i
.PHONY : src/commands/reflog-yap.i

# target to preprocess a source file
src/commands/reflog-yap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/reflog-yap.c.i
.PHONY : src/commands/reflog-yap.c.i

src/commands/reflog-yap.s: src/commands/reflog-yap.c.s
.PHONY : src/commands/reflog-yap.s

# target to generate assembly for a file
src/commands/reflog-yap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/reflog-yap.c.s
.PHONY : src/commands/reflog-yap.c.s

src/commands/rewind.o: src/commands/rewind.c.o
.PHONY : src/commands/rewind.o

# target to build an object file
src/commands/rewind.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rewind.c.o
.PHONY : src/commands/rewind.c.o

src/commands/rewind.i: src/commands/rewind.c.i
.PHONY : src/commands/rewind.i

# target to preprocess a source file
src/commands/rewind.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rewind.c.i
.PHONY : src/commands/rewind.c.i

src/commands/rewind.s: src/commands/rewind.c.s
.PHONY : src/commands/rewind.s

# target to generate assembly for a file
src/commands/rewind.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rewind.c.s
.PHONY : src/commands/rewind.c.s

src/commands/rip-branch.o: src/commands/rip-branch.c.o
.PHONY : src/commands/rip-branch.o

# target to build an object file
src/commands/rip-branch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rip-branch.c.o
.PHONY : src/commands/rip-branch.c.o

src/commands/rip-branch.i: src/commands/rip-branch.c.i
.PHONY : src/commands/rip-branch.i

# target to preprocess a source file
src/commands/rip-branch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rip-branch.c.i
.PHONY : src/commands/rip-branch.c.i

src/commands/rip-branch.s: src/commands/rip-branch.c.s
.PHONY : src/commands/rip-branch.s

# target to generate assembly for a file
src/commands/rip-branch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/rip-branch.c.s
.PHONY : src/commands/rip-branch.c.s

src/commands/roast.o: src/commands/roast.c.o
.PHONY : src/commands/roast.o

# target to build an object file
src/commands/roast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/roast.c.o
.PHONY : src/commands/roast.c.o

src/commands/roast.i: src/commands/roast.c.i
.PHONY : src/commands/roast.i

# target to preprocess a source file
src/commands/roast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/roast.c.i
.PHONY : src/commands/roast.c.i

src/commands/roast.s: src/commands/roast.c.s
.PHONY : src/commands/roast.s

# target to generate assembly for a file
src/commands/roast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/roast.c.s
.PHONY : src/commands/roast.c.s

src/commands/scrub.o: src/commands/scrub.c.o
.PHONY : src/commands/scrub.o

# target to build an object file
src/commands/scrub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/scrub.c.o
.PHONY : src/commands/scrub.c.o

src/commands/scrub.i: src/commands/scrub.c.i
.PHONY : src/commands/scrub.i

# target to preprocess a source file
src/commands/scrub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/scrub.c.i
.PHONY : src/commands/scrub.c.i

src/commands/scrub.s: src/commands/scrub.c.s
.PHONY : src/commands/scrub.s

# target to generate assembly for a file
src/commands/scrub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/scrub.c.s
.PHONY : src/commands/scrub.c.s

src/commands/search-bro.o: src/commands/search-bro.c.o
.PHONY : src/commands/search-bro.o

# target to build an object file
src/commands/search-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/search-bro.c.o
.PHONY : src/commands/search-bro.c.o

src/commands/search-bro.i: src/commands/search-bro.c.i
.PHONY : src/commands/search-bro.i

# target to preprocess a source file
src/commands/search-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/search-bro.c.i
.PHONY : src/commands/search-bro.c.i

src/commands/search-bro.s: src/commands/search-bro.c.s
.PHONY : src/commands/search-bro.s

# target to generate assembly for a file
src/commands/search-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/search-bro.c.s
.PHONY : src/commands/search-bro.c.s

src/commands/sidekick.o: src/commands/sidekick.c.o
.PHONY : src/commands/sidekick.o

# target to build an object file
src/commands/sidekick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sidekick.c.o
.PHONY : src/commands/sidekick.c.o

src/commands/sidekick.i: src/commands/sidekick.c.i
.PHONY : src/commands/sidekick.i

# target to preprocess a source file
src/commands/sidekick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sidekick.c.i
.PHONY : src/commands/sidekick.c.i

src/commands/sidekick.s: src/commands/sidekick.c.s
.PHONY : src/commands/sidekick.s

# target to generate assembly for a file
src/commands/sidekick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sidekick.c.s
.PHONY : src/commands/sidekick.c.s

src/commands/slap.o: src/commands/slap.c.o
.PHONY : src/commands/slap.o

# target to build an object file
src/commands/slap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/slap.c.o
.PHONY : src/commands/slap.c.o

src/commands/slap.i: src/commands/slap.c.i
.PHONY : src/commands/slap.i

# target to preprocess a source file
src/commands/slap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/slap.c.i
.PHONY : src/commands/slap.c.i

src/commands/slap.s: src/commands/slap.c.s
.PHONY : src/commands/slap.s

# target to generate assembly for a file
src/commands/slap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/slap.c.s
.PHONY : src/commands/slap.c.s

src/commands/snitch.o: src/commands/snitch.c.o
.PHONY : src/commands/snitch.o

# target to build an object file
src/commands/snitch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/snitch.c.o
.PHONY : src/commands/snitch.c.o

src/commands/snitch.i: src/commands/snitch.c.i
.PHONY : src/commands/snitch.i

# target to preprocess a source file
src/commands/snitch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/snitch.c.i
.PHONY : src/commands/snitch.c.i

src/commands/snitch.s: src/commands/snitch.c.s
.PHONY : src/commands/snitch.s

# target to generate assembly for a file
src/commands/snitch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/snitch.c.s
.PHONY : src/commands/snitch.c.s

src/commands/soft-undo.o: src/commands/soft-undo.c.o
.PHONY : src/commands/soft-undo.o

# target to build an object file
src/commands/soft-undo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/soft-undo.c.o
.PHONY : src/commands/soft-undo.c.o

src/commands/soft-undo.i: src/commands/soft-undo.c.i
.PHONY : src/commands/soft-undo.i

# target to preprocess a source file
src/commands/soft-undo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/soft-undo.c.i
.PHONY : src/commands/soft-undo.c.i

src/commands/soft-undo.s: src/commands/soft-undo.c.s
.PHONY : src/commands/soft-undo.s

# target to generate assembly for a file
src/commands/soft-undo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/soft-undo.c.s
.PHONY : src/commands/soft-undo.c.s

src/commands/squad.o: src/commands/squad.c.o
.PHONY : src/commands/squad.o

# target to build an object file
src/commands/squad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/squad.c.o
.PHONY : src/commands/squad.c.o

src/commands/squad.i: src/commands/squad.c.i
.PHONY : src/commands/squad.i

# target to preprocess a source file
src/commands/squad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/squad.c.i
.PHONY : src/commands/squad.c.i

src/commands/squad.s: src/commands/squad.c.s
.PHONY : src/commands/squad.s

# target to generate assembly for a file
src/commands/squad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/squad.c.s
.PHONY : src/commands/squad.c.s

src/commands/steal.o: src/commands/steal.c.o
.PHONY : src/commands/steal.o

# target to build an object file
src/commands/steal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/steal.c.o
.PHONY : src/commands/steal.c.o

src/commands/steal.i: src/commands/steal.c.i
.PHONY : src/commands/steal.i

# target to preprocess a source file
src/commands/steal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/steal.c.i
.PHONY : src/commands/steal.c.i

src/commands/steal.s: src/commands/steal.c.s
.PHONY : src/commands/steal.s

# target to generate assembly for a file
src/commands/steal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/steal.c.s
.PHONY : src/commands/steal.c.s

src/commands/sticky-note.o: src/commands/sticky-note.c.o
.PHONY : src/commands/sticky-note.o

# target to build an object file
src/commands/sticky-note.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sticky-note.c.o
.PHONY : src/commands/sticky-note.c.o

src/commands/sticky-note.i: src/commands/sticky-note.c.i
.PHONY : src/commands/sticky-note.i

# target to preprocess a source file
src/commands/sticky-note.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sticky-note.c.i
.PHONY : src/commands/sticky-note.c.i

src/commands/sticky-note.s: src/commands/sticky-note.c.s
.PHONY : src/commands/sticky-note.s

# target to generate assembly for a file
src/commands/sticky-note.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/sticky-note.c.s
.PHONY : src/commands/sticky-note.c.s

src/commands/summary.o: src/commands/summary.c.o
.PHONY : src/commands/summary.o

# target to build an object file
src/commands/summary.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/summary.c.o
.PHONY : src/commands/summary.c.o

src/commands/summary.i: src/commands/summary.c.i
.PHONY : src/commands/summary.i

# target to preprocess a source file
src/commands/summary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/summary.c.i
.PHONY : src/commands/summary.c.i

src/commands/summary.s: src/commands/summary.c.s
.PHONY : src/commands/summary.s

# target to generate assembly for a file
src/commands/summary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/summary.c.s
.PHONY : src/commands/summary.c.s

src/commands/teleport.o: src/commands/teleport.c.o
.PHONY : src/commands/teleport.o

# target to build an object file
src/commands/teleport.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/teleport.c.o
.PHONY : src/commands/teleport.c.o

src/commands/teleport.i: src/commands/teleport.c.i
.PHONY : src/commands/teleport.i

# target to preprocess a source file
src/commands/teleport.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/teleport.c.i
.PHONY : src/commands/teleport.c.i

src/commands/teleport.s: src/commands/teleport.c.s
.PHONY : src/commands/teleport.s

# target to generate assembly for a file
src/commands/teleport.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/teleport.c.s
.PHONY : src/commands/teleport.c.s

src/commands/time-machine.o: src/commands/time-machine.c.o
.PHONY : src/commands/time-machine.o

# target to build an object file
src/commands/time-machine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/time-machine.c.o
.PHONY : src/commands/time-machine.c.o

src/commands/time-machine.i: src/commands/time-machine.c.i
.PHONY : src/commands/time-machine.i

# target to preprocess a source file
src/commands/time-machine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/time-machine.c.i
.PHONY : src/commands/time-machine.c.i

src/commands/time-machine.s: src/commands/time-machine.c.s
.PHONY : src/commands/time-machine.s

# target to generate assembly for a file
src/commands/time-machine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/time-machine.c.s
.PHONY : src/commands/time-machine.c.s

src/commands/tui.o: src/commands/tui.c.o
.PHONY : src/commands/tui.o

# target to build an object file
src/commands/tui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/tui.c.o
.PHONY : src/commands/tui.c.o

src/commands/tui.i: src/commands/tui.c.i
.PHONY : src/commands/tui.i

# target to preprocess a source file
src/commands/tui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/tui.c.i
.PHONY : src/commands/tui.c.i

src/commands/tui.s: src/commands/tui.c.s
.PHONY : src/commands/tui.s

# target to generate assembly for a file
src/commands/tui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/tui.c.s
.PHONY : src/commands/tui.c.s

src/commands/undo-vibes.o: src/commands/undo-vibes.c.o
.PHONY : src/commands/undo-vibes.o

# target to build an object file
src/commands/undo-vibes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/undo-vibes.c.o
.PHONY : src/commands/undo-vibes.c.o

src/commands/undo-vibes.i: src/commands/undo-vibes.c.i
.PHONY : src/commands/undo-vibes.i

# target to preprocess a source file
src/commands/undo-vibes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/undo-vibes.c.i
.PHONY : src/commands/undo-vibes.c.i

src/commands/undo-vibes.s: src/commands/undo-vibes.c.s
.PHONY : src/commands/undo-vibes.s

# target to generate assembly for a file
src/commands/undo-vibes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/undo-vibes.c.s
.PHONY : src/commands/undo-vibes.c.s

src/commands/unstage-slap.o: src/commands/unstage-slap.c.o
.PHONY : src/commands/unstage-slap.o

# target to build an object file
src/commands/unstage-slap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/unstage-slap.c.o
.PHONY : src/commands/unstage-slap.c.o

src/commands/unstage-slap.i: src/commands/unstage-slap.c.i
.PHONY : src/commands/unstage-slap.i

# target to preprocess a source file
src/commands/unstage-slap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/unstage-slap.c.i
.PHONY : src/commands/unstage-slap.c.i

src/commands/unstage-slap.s: src/commands/unstage-slap.c.s
.PHONY : src/commands/unstage-slap.s

# target to generate assembly for a file
src/commands/unstage-slap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/unstage-slap.c.s
.PHONY : src/commands/unstage-slap.c.s

src/commands/untrack-bro.o: src/commands/untrack-bro.c.o
.PHONY : src/commands/untrack-bro.o

# target to build an object file
src/commands/untrack-bro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/untrack-bro.c.o
.PHONY : src/commands/untrack-bro.c.o

src/commands/untrack-bro.i: src/commands/untrack-bro.c.i
.PHONY : src/commands/untrack-bro.i

# target to preprocess a source file
src/commands/untrack-bro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/untrack-bro.c.i
.PHONY : src/commands/untrack-bro.c.i

src/commands/untrack-bro.s: src/commands/untrack-bro.c.s
.PHONY : src/commands/untrack-bro.s

# target to generate assembly for a file
src/commands/untrack-bro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/untrack-bro.c.s
.PHONY : src/commands/untrack-bro.c.s

src/commands/vibe-check.o: src/commands/vibe-check.c.o
.PHONY : src/commands/vibe-check.o

# target to build an object file
src/commands/vibe-check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/vibe-check.c.o
.PHONY : src/commands/vibe-check.c.o

src/commands/vibe-check.i: src/commands/vibe-check.c.i
.PHONY : src/commands/vibe-check.i

# target to preprocess a source file
src/commands/vibe-check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/vibe-check.c.i
.PHONY : src/commands/vibe-check.c.i

src/commands/vibe-check.s: src/commands/vibe-check.c.s
.PHONY : src/commands/vibe-check.s

# target to generate assembly for a file
src/commands/vibe-check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/vibe-check.c.s
.PHONY : src/commands/vibe-check.c.s

src/commands/who-dis.o: src/commands/who-dis.c.o
.PHONY : src/commands/who-dis.o

# target to build an object file
src/commands/who-dis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/who-dis.c.o
.PHONY : src/commands/who-dis.c.o

src/commands/who-dis.i: src/commands/who-dis.c.i
.PHONY : src/commands/who-dis.i

# target to preprocess a source file
src/commands/who-dis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/who-dis.c.i
.PHONY : src/commands/who-dis.c.i

src/commands/who-dis.s: src/commands/who-dis.c.s
.PHONY : src/commands/who-dis.s

# target to generate assembly for a file
src/commands/who-dis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/who-dis.c.s
.PHONY : src/commands/who-dis.c.s

src/commands/yap.o: src/commands/yap.c.o
.PHONY : src/commands/yap.o

# target to build an object file
src/commands/yap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yap.c.o
.PHONY : src/commands/yap.c.o

src/commands/yap.i: src/commands/yap.c.i
.PHONY : src/commands/yap.i

# target to preprocess a source file
src/commands/yap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yap.c.i
.PHONY : src/commands/yap.c.i

src/commands/yap.s: src/commands/yap.c.s
.PHONY : src/commands/yap.s

# target to generate assembly for a file
src/commands/yap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yap.c.s
.PHONY : src/commands/yap.c.s

src/commands/yeet-file.o: src/commands/yeet-file.c.o
.PHONY : src/commands/yeet-file.o

# target to build an object file
src/commands/yeet-file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet-file.c.o
.PHONY : src/commands/yeet-file.c.o

src/commands/yeet-file.i: src/commands/yeet-file.c.i
.PHONY : src/commands/yeet-file.i

# target to preprocess a source file
src/commands/yeet-file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet-file.c.i
.PHONY : src/commands/yeet-file.c.i

src/commands/yeet-file.s: src/commands/yeet-file.c.s
.PHONY : src/commands/yeet-file.s

# target to generate assembly for a file
src/commands/yeet-file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet-file.c.s
.PHONY : src/commands/yeet-file.c.s

src/commands/yeet.o: src/commands/yeet.c.o
.PHONY : src/commands/yeet.o

# target to build an object file
src/commands/yeet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet.c.o
.PHONY : src/commands/yeet.c.o

src/commands/yeet.i: src/commands/yeet.c.i
.PHONY : src/commands/yeet.i

# target to preprocess a source file
src/commands/yeet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet.c.i
.PHONY : src/commands/yeet.c.i

src/commands/yeet.s: src/commands/yeet.c.s
.PHONY : src/commands/yeet.s

# target to generate assembly for a file
src/commands/yeet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yeet.c.s
.PHONY : src/commands/yeet.c.s

src/commands/yoink-cherry.o: src/commands/yoink-cherry.c.o
.PHONY : src/commands/yoink-cherry.o

# target to build an object file
src/commands/yoink-cherry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink-cherry.c.o
.PHONY : src/commands/yoink-cherry.c.o

src/commands/yoink-cherry.i: src/commands/yoink-cherry.c.i
.PHONY : src/commands/yoink-cherry.i

# target to preprocess a source file
src/commands/yoink-cherry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink-cherry.c.i
.PHONY : src/commands/yoink-cherry.c.i

src/commands/yoink-cherry.s: src/commands/yoink-cherry.c.s
.PHONY : src/commands/yoink-cherry.s

# target to generate assembly for a file
src/commands/yoink-cherry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink-cherry.c.s
.PHONY : src/commands/yoink-cherry.c.s

src/commands/yoink.o: src/commands/yoink.c.o
.PHONY : src/commands/yoink.o

# target to build an object file
src/commands/yoink.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink.c.o
.PHONY : src/commands/yoink.c.o

src/commands/yoink.i: src/commands/yoink.c.i
.PHONY : src/commands/yoink.i

# target to preprocess a source file
src/commands/yoink.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink.c.i
.PHONY : src/commands/yoink.c.i

src/commands/yoink.s: src/commands/yoink.c.s
.PHONY : src/commands/yoink.s

# target to generate assembly for a file
src/commands/yoink.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/yoink.c.s
.PHONY : src/commands/yoink.c.s

src/commands/zip-pack.o: src/commands/zip-pack.c.o
.PHONY : src/commands/zip-pack.o

# target to build an object file
src/commands/zip-pack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/zip-pack.c.o
.PHONY : src/commands/zip-pack.c.o

src/commands/zip-pack.i: src/commands/zip-pack.c.i
.PHONY : src/commands/zip-pack.i

# target to preprocess a source file
src/commands/zip-pack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/zip-pack.c.i
.PHONY : src/commands/zip-pack.c.i

src/commands/zip-pack.s: src/commands/zip-pack.c.s
.PHONY : src/commands/zip-pack.s

# target to generate assembly for a file
src/commands/zip-pack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/commands/zip-pack.c.s
.PHONY : src/commands/zip-pack.c.s

src/core/blob.o: src/core/blob.c.o
.PHONY : src/core/blob.o

# target to build an object file
src/core/blob.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/blob.c.o
.PHONY : src/core/blob.c.o

src/core/blob.i: src/core/blob.c.i
.PHONY : src/core/blob.i

# target to preprocess a source file
src/core/blob.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/blob.c.i
.PHONY : src/core/blob.c.i

src/core/blob.s: src/core/blob.c.s
.PHONY : src/core/blob.s

# target to generate assembly for a file
src/core/blob.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/blob.c.s
.PHONY : src/core/blob.c.s

src/core/commit.o: src/core/commit.c.o
.PHONY : src/core/commit.o

# target to build an object file
src/core/commit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/commit.c.o
.PHONY : src/core/commit.c.o

src/core/commit.i: src/core/commit.c.i
.PHONY : src/core/commit.i

# target to preprocess a source file
src/core/commit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/commit.c.i
.PHONY : src/core/commit.c.i

src/core/commit.s: src/core/commit.c.s
.PHONY : src/core/commit.s

# target to generate assembly for a file
src/core/commit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/commit.c.s
.PHONY : src/core/commit.c.s

src/core/object.o: src/core/object.c.o
.PHONY : src/core/object.o

# target to build an object file
src/core/object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/object.c.o
.PHONY : src/core/object.c.o

src/core/object.i: src/core/object.c.i
.PHONY : src/core/object.i

# target to preprocess a source file
src/core/object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/object.c.i
.PHONY : src/core/object.c.i

src/core/object.s: src/core/object.c.s
.PHONY : src/core/object.s

# target to generate assembly for a file
src/core/object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/object.c.s
.PHONY : src/core/object.c.s

src/core/odb.o: src/core/odb.c.o
.PHONY : src/core/odb.o

# target to build an object file
src/core/odb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/odb.c.o
.PHONY : src/core/odb.c.o

src/core/odb.i: src/core/odb.c.i
.PHONY : src/core/odb.i

# target to preprocess a source file
src/core/odb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/odb.c.i
.PHONY : src/core/odb.c.i

src/core/odb.s: src/core/odb.c.s
.PHONY : src/core/odb.s

# target to generate assembly for a file
src/core/odb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/odb.c.s
.PHONY : src/core/odb.c.s

src/core/sha1.o: src/core/sha1.c.o
.PHONY : src/core/sha1.o

# target to build an object file
src/core/sha1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/sha1.c.o
.PHONY : src/core/sha1.c.o

src/core/sha1.i: src/core/sha1.c.i
.PHONY : src/core/sha1.i

# target to preprocess a source file
src/core/sha1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/sha1.c.i
.PHONY : src/core/sha1.c.i

src/core/sha1.s: src/core/sha1.c.s
.PHONY : src/core/sha1.s

# target to generate assembly for a file
src/core/sha1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/sha1.c.s
.PHONY : src/core/sha1.c.s

src/core/tree.o: src/core/tree.c.o
.PHONY : src/core/tree.o

# target to build an object file
src/core/tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/tree.c.o
.PHONY : src/core/tree.c.o

src/core/tree.i: src/core/tree.c.i
.PHONY : src/core/tree.i

# target to preprocess a source file
src/core/tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/tree.c.i
.PHONY : src/core/tree.c.i

src/core/tree.s: src/core/tree.c.s
.PHONY : src/core/tree.s

# target to generate assembly for a file
src/core/tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/tree.c.s
.PHONY : src/core/tree.c.s

src/core/zlib_utils.o: src/core/zlib_utils.c.o
.PHONY : src/core/zlib_utils.o

# target to build an object file
src/core/zlib_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/zlib_utils.c.o
.PHONY : src/core/zlib_utils.c.o

src/core/zlib_utils.i: src/core/zlib_utils.c.i
.PHONY : src/core/zlib_utils.i

# target to preprocess a source file
src/core/zlib_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/zlib_utils.c.i
.PHONY : src/core/zlib_utils.c.i

src/core/zlib_utils.s: src/core/zlib_utils.c.s
.PHONY : src/core/zlib_utils.s

# target to generate assembly for a file
src/core/zlib_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/core/zlib_utils.c.s
.PHONY : src/core/zlib_utils.c.s

src/index.o: src/index.c.o
.PHONY : src/index.o

# target to build an object file
src/index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/index.c.o
.PHONY : src/index.c.o

src/index.i: src/index.c.i
.PHONY : src/index.i

# target to preprocess a source file
src/index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/index.c.i
.PHONY : src/index.c.i

src/index.s: src/index.c.s
.PHONY : src/index.s

# target to generate assembly for a file
src/index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/index.c.s
.PHONY : src/index.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/main.c.s
.PHONY : src/main.c.s

src/refs.o: src/refs.c.o
.PHONY : src/refs.o

# target to build an object file
src/refs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/refs.c.o
.PHONY : src/refs.c.o

src/refs.i: src/refs.c.i
.PHONY : src/refs.i

# target to preprocess a source file
src/refs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/refs.c.i
.PHONY : src/refs.c.i

src/refs.s: src/refs.c.s
.PHONY : src/refs.s

# target to generate assembly for a file
src/refs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/refs.c.s
.PHONY : src/refs.c.s

src/remote.o: src/remote.c.o
.PHONY : src/remote.o

# target to build an object file
src/remote.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/remote.c.o
.PHONY : src/remote.c.o

src/remote.i: src/remote.c.i
.PHONY : src/remote.i

# target to preprocess a source file
src/remote.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/remote.c.i
.PHONY : src/remote.c.i

src/remote.s: src/remote.c.s
.PHONY : src/remote.s

# target to generate assembly for a file
src/remote.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/remote.c.s
.PHONY : src/remote.c.s

src/repo.o: src/repo.c.o
.PHONY : src/repo.o

# target to build an object file
src/repo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/repo.c.o
.PHONY : src/repo.c.o

src/repo.i: src/repo.c.i
.PHONY : src/repo.i

# target to preprocess a source file
src/repo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/repo.c.i
.PHONY : src/repo.c.i

src/repo.s: src/repo.c.s
.PHONY : src/repo.s

# target to generate assembly for a file
src/repo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/repo.c.s
.PHONY : src/repo.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bro.dir/build.make CMakeFiles/bro.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bro"
	@echo "... src/commands/absorb.o"
	@echo "... src/commands/absorb.i"
	@echo "... src/commands/absorb.s"
	@echo "... src/commands/amend-yeet.o"
	@echo "... src/commands/amend-yeet.i"
	@echo "... src/commands/amend-yeet.s"
	@echo "... src/commands/apply-mail.o"
	@echo "... src/commands/apply-mail.i"
	@echo "... src/commands/apply-mail.s"
	@echo "... src/commands/archive-vibes.o"
	@echo "... src/commands/archive-vibes.i"
	@echo "... src/commands/archive-vibes.s"
	@echo "... src/commands/blame-grep.o"
	@echo "... src/commands/blame-grep.i"
	@echo "... src/commands/blame-grep.s"
	@echo "... src/commands/bro-doctor.o"
	@echo "... src/commands/bro-doctor.i"
	@echo "... src/commands/bro-doctor.s"
	@echo "... src/commands/clean-house.o"
	@echo "... src/commands/clean-house.i"
	@echo "... src/commands/clean-house.s"
	@echo "... src/commands/config-vibe.o"
	@echo "... src/commands/config-vibe.i"
	@echo "... src/commands/config-vibe.s"
	@echo "... src/commands/delete-bro.o"
	@echo "... src/commands/delete-bro.i"
	@echo "... src/commands/delete-bro.s"
	@echo "... src/commands/detective.o"
	@echo "... src/commands/detective.i"
	@echo "... src/commands/detective.s"
	@echo "... src/commands/diff-bro.o"
	@echo "... src/commands/diff-bro.i"
	@echo "... src/commands/diff-bro.s"
	@echo "... src/commands/drip.o"
	@echo "... src/commands/drip.i"
	@echo "... src/commands/drip.s"
	@echo "... src/commands/expose.o"
	@echo "... src/commands/expose.i"
	@echo "... src/commands/expose.s"
	@echo "... src/commands/force-launch.o"
	@echo "... src/commands/force-launch.i"
	@echo "... src/commands/force-launch.s"
	@echo "... src/commands/fuse.o"
	@echo "... src/commands/fuse.i"
	@echo "... src/commands/fuse.s"
	@echo "... src/commands/grep-it.o"
	@echo "... src/commands/grep-it.i"
	@echo "... src/commands/grep-it.s"
	@echo "... src/commands/hard-undo.o"
	@echo "... src/commands/hard-undo.i"
	@echo "... src/commands/hard-undo.s"
	@echo "... src/commands/hash-slap.o"
	@echo "... src/commands/hash-slap.i"
	@echo "... src/commands/hash-slap.s"
	@echo "... src/commands/hide.o"
	@echo "... src/commands/hide.i"
	@echo "... src/commands/hide.s"
	@echo "... src/commands/ignore-bro.o"
	@echo "... src/commands/ignore-bro.i"
	@echo "... src/commands/ignore-bro.s"
	@echo "... src/commands/init.o"
	@echo "... src/commands/init.i"
	@echo "... src/commands/init.s"
	@echo "... src/commands/launch.o"
	@echo "... src/commands/launch.i"
	@echo "... src/commands/launch.s"
	@echo "... src/commands/live.o"
	@echo "... src/commands/live.i"
	@echo "... src/commands/live.s"
	@echo "... src/commands/ls-bro.o"
	@echo "... src/commands/ls-bro.i"
	@echo "... src/commands/ls-bro.s"
	@echo "... src/commands/multiverse.o"
	@echo "... src/commands/multiverse.i"
	@echo "... src/commands/multiverse.s"
	@echo "... src/commands/new-squad.o"
	@echo "... src/commands/new-squad.i"
	@echo "... src/commands/new-squad.s"
	@echo "... src/commands/nickname.o"
	@echo "... src/commands/nickname.i"
	@echo "... src/commands/nickname.s"
	@echo "... src/commands/only-fans.o"
	@echo "... src/commands/only-fans.i"
	@echo "... src/commands/only-fans.s"
	@echo "... src/commands/oopsie.o"
	@echo "... src/commands/oopsie.i"
	@echo "... src/commands/oopsie.s"
	@echo "... src/commands/panic-revert.o"
	@echo "... src/commands/panic-revert.i"
	@echo "... src/commands/panic-revert.s"
	@echo "... src/commands/patch-mail.o"
	@echo "... src/commands/patch-mail.i"
	@echo "... src/commands/patch-mail.s"
	@echo "... src/commands/peek.o"
	@echo "... src/commands/peek.i"
	@echo "... src/commands/peek.s"
	@echo "... src/commands/range-roast.o"
	@echo "... src/commands/range-roast.i"
	@echo "... src/commands/range-roast.s"
	@echo "... src/commands/reflog-yap.o"
	@echo "... src/commands/reflog-yap.i"
	@echo "... src/commands/reflog-yap.s"
	@echo "... src/commands/rewind.o"
	@echo "... src/commands/rewind.i"
	@echo "... src/commands/rewind.s"
	@echo "... src/commands/rip-branch.o"
	@echo "... src/commands/rip-branch.i"
	@echo "... src/commands/rip-branch.s"
	@echo "... src/commands/roast.o"
	@echo "... src/commands/roast.i"
	@echo "... src/commands/roast.s"
	@echo "... src/commands/scrub.o"
	@echo "... src/commands/scrub.i"
	@echo "... src/commands/scrub.s"
	@echo "... src/commands/search-bro.o"
	@echo "... src/commands/search-bro.i"
	@echo "... src/commands/search-bro.s"
	@echo "... src/commands/sidekick.o"
	@echo "... src/commands/sidekick.i"
	@echo "... src/commands/sidekick.s"
	@echo "... src/commands/slap.o"
	@echo "... src/commands/slap.i"
	@echo "... src/commands/slap.s"
	@echo "... src/commands/snitch.o"
	@echo "... src/commands/snitch.i"
	@echo "... src/commands/snitch.s"
	@echo "... src/commands/soft-undo.o"
	@echo "... src/commands/soft-undo.i"
	@echo "... src/commands/soft-undo.s"
	@echo "... src/commands/squad.o"
	@echo "... src/commands/squad.i"
	@echo "... src/commands/squad.s"
	@echo "... src/commands/steal.o"
	@echo "... src/commands/steal.i"
	@echo "... src/commands/steal.s"
	@echo "... src/commands/sticky-note.o"
	@echo "... src/commands/sticky-note.i"
	@echo "... src/commands/sticky-note.s"
	@echo "... src/commands/summary.o"
	@echo "... src/commands/summary.i"
	@echo "... src/commands/summary.s"
	@echo "... src/commands/teleport.o"
	@echo "... src/commands/teleport.i"
	@echo "... src/commands/teleport.s"
	@echo "... src/commands/time-machine.o"
	@echo "... src/commands/time-machine.i"
	@echo "... src/commands/time-machine.s"
	@echo "... src/commands/tui.o"
	@echo "... src/commands/tui.i"
	@echo "... src/commands/tui.s"
	@echo "... src/commands/undo-vibes.o"
	@echo "... src/commands/undo-vibes.i"
	@echo "... src/commands/undo-vibes.s"
	@echo "... src/commands/unstage-slap.o"
	@echo "... src/commands/unstage-slap.i"
	@echo "... src/commands/unstage-slap.s"
	@echo "... src/commands/untrack-bro.o"
	@echo "... src/commands/untrack-bro.i"
	@echo "... src/commands/untrack-bro.s"
	@echo "... src/commands/vibe-check.o"
	@echo "... src/commands/vibe-check.i"
	@echo "... src/commands/vibe-check.s"
	@echo "... src/commands/who-dis.o"
	@echo "... src/commands/who-dis.i"
	@echo "... src/commands/who-dis.s"
	@echo "... src/commands/yap.o"
	@echo "... src/commands/yap.i"
	@echo "... src/commands/yap.s"
	@echo "... src/commands/yeet-file.o"
	@echo "... src/commands/yeet-file.i"
	@echo "... src/commands/yeet-file.s"
	@echo "... src/commands/yeet.o"
	@echo "... src/commands/yeet.i"
	@echo "... src/commands/yeet.s"
	@echo "... src/commands/yoink-cherry.o"
	@echo "... src/commands/yoink-cherry.i"
	@echo "... src/commands/yoink-cherry.s"
	@echo "... src/commands/yoink.o"
	@echo "... src/commands/yoink.i"
	@echo "... src/commands/yoink.s"
	@echo "... src/commands/zip-pack.o"
	@echo "... src/commands/zip-pack.i"
	@echo "... src/commands/zip-pack.s"
	@echo "... src/core/blob.o"
	@echo "... src/core/blob.i"
	@echo "... src/core/blob.s"
	@echo "... src/core/commit.o"
	@echo "... src/core/commit.i"
	@echo "... src/core/commit.s"
	@echo "... src/core/object.o"
	@echo "... src/core/object.i"
	@echo "... src/core/object.s"
	@echo "... src/core/odb.o"
	@echo "... src/core/odb.i"
	@echo "... src/core/odb.s"
	@echo "... src/core/sha1.o"
	@echo "... src/core/sha1.i"
	@echo "... src/core/sha1.s"
	@echo "... src/core/tree.o"
	@echo "... src/core/tree.i"
	@echo "... src/core/tree.s"
	@echo "... src/core/zlib_utils.o"
	@echo "... src/core/zlib_utils.i"
	@echo "... src/core/zlib_utils.s"
	@echo "... src/index.o"
	@echo "... src/index.i"
	@echo "... src/index.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/refs.o"
	@echo "... src/refs.i"
	@echo "... src/refs.s"
	@echo "... src/remote.o"
	@echo "... src/remote.i"
	@echo "... src/remote.s"
	@echo "... src/repo.o"
	@echo "... src/repo.i"
	@echo "... src/repo.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

